language: ruby
rvm:
  - 2.2.0
bundler_args: '--without development production'
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq imagemagick
before_script:
  - 'cp config/application.example.yml config/application.yml'
  - 'bundle exec rake db:migrate'
