language: ruby
rvm:
  - 2.1.1
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq nodejs imagemagick
before_script:
  - 'cp config/app_config.example.yml config/app_config.yml'
  - "psql -c 'create database mawidabp_test;' -U postgres"
  - 'bundle exec rake db:migrate'
