language: ruby
cache: bundler
sudo: false
rvm:
  - 2.3.5
  - 2.4.2

addons:
  apt:
    packages:
    - imagemagick
    - slapd
    - ldap-utils
  postgresql: 9.6

env:
  - ALLOW_REVIEW_CONTROL_OBJECTIVE_DUPLICATION=false DISABLE_FINDINGS_EXPIRATION_NOTIFICATION=false DISABLE_REVIEW_AUDITED_VALIDATION_ON_CREATION=false HIDE_BUSINESS_UNIT_SCORES=false HIDE_CONTROL_EFFECTS=false HIDE_CONTROL_OBJECTIVE_ITEM_EFFECTIVENESS=false HIDE_CONTROL_OBJECTIVE_RISK=false HIDE_FINDING_CRITERIA_MISMATCH=false HIDE_FINDING_REVOKED=false HIDE_OPORTUNITIES=false HIDE_REVIEW_DESCRIPTION=false HIDE_WEAKNESS_EFFECT=false HIDE_WEAKNESS_PRIORITY=false ORDER_REVIEWS_BY='period' SHOW_ASSUMED_RISK_AS_REVIEW_PENDING=false SHOW_CONCLUSION_ALTERNATIVE_PDF=false SHOW_CONCLUSION_AS_OPTIONS=false SHOW_EXTENDED_RISKS=false SHOW_FINDING_CURRENT_SITUATION=false SHOW_REVIEW_EXTRA_ATTRIBUTES=false SHOW_REVIEW_AUTOMATIC_IDENTIFICATION=false SHOW_WEAKNESS_EXTRA_ATTRIBUTES=false SHOW_WEAKNESS_PROGRESS=false USE_SHORT_RELEVANCE=false
  - ALLOW_REVIEW_CONTROL_OBJECTIVE_DUPLICATION=true DISABLE_FINDINGS_EXPIRATION_NOTIFICATION=true DISABLE_REVIEW_AUDITED_VALIDATION_ON_CREATION=true HIDE_BUSINESS_UNIT_SCORES=true HIDE_CONTROL_EFFECTS=true HIDE_CONTROL_OBJECTIVE_ITEM_EFFECTIVENESS=true HIDE_CONTROL_OBJECTIVE_RISK=true HIDE_FINDING_CRITERIA_MISMATCH=true HIDE_FINDING_REVOKED=true HIDE_OPORTUNITIES=true HIDE_REVIEW_DESCRIPTION=true HIDE_WEAKNESS_EFFECT=true HIDE_WEAKNESS_PRIORITY=true ORDER_REVIEWS_BY='conclusion_final_review' SHOW_ASSUMED_RISK_AS_REVIEW_PENDING=true SHOW_CONCLUSION_ALTERNATIVE_PDF=true SHOW_CONCLUSION_AS_OPTIONS=true SHOW_EXTENDED_RISKS=true SHOW_FINDING_CURRENT_SITUATION=true SHOW_REVIEW_AUTOMATIC_IDENTIFICATION=true SHOW_REVIEW_EXTRA_ATTRIBUTES=true SHOW_WEAKNESS_EXTRA_ATTRIBUTES=true SHOW_WEAKNESS_PROGRESS=true USE_SHORT_RELEVANCE=true

before_script:
  - 'cp config/application.example.yml config/application.yml'
  - "psql -c 'create database mawidabp_test;' -U postgres"
  - 'bundle exec rake db:migrate'
  - 'slapd -f test/fixtures/ldap/slapd.conf -h ldap://localhost:3389'
  - 'bundle exec rake ldap:reset'
