language: ruby
cache: bundler
sudo: required
dist: trusty
rvm:
  - 2.3.3
  - 2.4.1
addons:
  apt:
    packages:
    - imagemagick
    - slapd
    - ldap-utils
  postgresql: 9.5
before_script:
  - 'cp config/application.example.yml config/application.yml'
  - "psql -c 'create database mawidabp_test;' -U postgres"
  - 'bundle exec rake db:migrate'
  - 'slapd -f test/fixtures/ldap/slapd.conf -h ldap://localhost:3389'
  - 'bundle exec rake ldap:reset'
