language: ruby
rvm:
  - 1.9.3
  - 2.0.0
services:
  - memcache
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq nodejs imagemagick
before_script:
  - 'cp config/app_config.example.yml config/app_config.yml'
  - "psql -c 'create database mawida_test;' -U postgres"
  - 'bundle exec rake db:migrate'
