language: ruby
cache: bundler
sudo: false
rvm:
  - 2.5.2
bundler_args: '--without development production'

addons:
  apt:
    packages:
    - imagemagick
    - slapd
    - ldap-utils

env:
  - CONFIG_TYPE=normal
  - CONFIG_TYPE=alternative
  - CONFIG_TYPE=reviews_scored_by_weakness

before_install:
  - 'gem install bundler'

before_script:
  - 'cp config/application.yml.example config/application.yml'
  - 'cp config/database.travis.yml config/database.yml'
  - 'bundle exec rake db:migrate'
  - 'slapd -f test/fixtures/ldap/slapd.conf -h ldap://localhost:3389'
  - 'bundle exec rake ldap:reset'
