language: ruby
rvm:
  - 1.8.7
  - ree
before_script:
  - 'cp config/app_config.example.yml config/app_config.yml'
  - "psql -c 'create database mawida_test;' -U postgres"
  - 'bundle exec rake db:migrate'
