language: ruby
cache: bundler
sudo: false
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.2

addons:
  apt:
    packages:
    - imagemagick
    - slapd
    - ldap-utils
  postgresql: 9.6

env:
  - CONFIG_TYPE=normal
  - CONFIG_TYPE=alternative
  - CONFIG_TYPE=reviews_scored_by_weakness

before_install:
  - 'gem install bundler'

before_script:
  - 'cp config/application.yml.example config/application.yml'
  - "psql -c 'create database mawidabp_test;' -U postgres"
  - 'bundle exec rake db:migrate'
  - 'slapd -f test/fixtures/ldap/slapd.conf -h ldap://localhost:3389'
  - 'bundle exec rake ldap:reset'
