language: ruby
cache: bundler
sudo: false
rvm:
  - 2.3.5
  - 2.4.2

addons:
  apt:
    packages:
    - imagemagick
    - slapd
    - ldap-utils
  postgresql: 9.6

env:
  - DISABLE_FINDINGS_EXPIRATION_NOTIFICATION=false HIDE_BUSINESS_UNIT_SCORES=false HIDE_CONTROL_OBJECTIVE_ITEM_EFFECTIVENESS=false HIDE_CONTROL_OBJECTIVE_RISK=false HIDE_OPORTUNITIES=false HIDE_REVIEW_DESCRIPTION=false HIDE_WEAKNESS_PRIORITY=false SHOW_CONTROL_OBJECTIVE_ITEM_AUDITOR_COMMENT_AS_OPTIONS=false SHOW_EXTENDED_RISKS=false SHOW_WEAKNESS_PROGRESS=false USE_SHORT_RELEVANCE=false
  - DISABLE_FINDINGS_EXPIRATION_NOTIFICATION=true HIDE_BUSINESS_UNIT_SCORES=true HIDE_CONTROL_OBJECTIVE_ITEM_EFFECTIVENESS=true HIDE_CONTROL_OBJECTIVE_RISK=true HIDE_OPORTUNITIES=true HIDE_REVIEW_DESCRIPTION=true HIDE_WEAKNESS_PRIORITY=true SHOW_CONTROL_OBJECTIVE_ITEM_AUDITOR_COMMENT_AS_OPTIONS=true SHOW_EXTENDED_RISKS=true SHOW_WEAKNESS_PROGRESS=true USE_SHORT_RELEVANCE=true

before_script:
  - 'cp config/application.example.yml config/application.yml'
  - "psql -c 'create database mawidabp_test;' -U postgres"
  - 'bundle exec rake db:migrate'
  - 'slapd -f test/fixtures/ldap/slapd.conf -h ldap://localhost:3389'
  - 'bundle exec rake ldap:reset'
