language: ruby
rvm:
  - 2.2.0
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq imagemagick
before_script:
  - 'cp config/application.example.yml config/application.yml'
  - "psql -c 'create database mawidabp_test;' -U postgres"
  - 'bundle exec rake db:migrate'
