language: ruby
dist: bionic
cache: bundler
rvm:
  - 2.6.6
  - 2.7.1

addons:
  apt:
    packages:
    - imagemagick
    - slapd
    - ldap-utils
  postgresql: 11

services:
  - postgresql
  - redis-server

env:
  global:
    - secure: PwjUL6m4vu2TzZIiIP/OMzKvnqbSW+TNRkcy6eelNyGwvDUcO6ylRA7xFSQn0P+bulYFWdeQJ/AUcHxu+FvwKJp+0MWf/CvKYlyI1i4+cPNErigUVEY4wmN4UI7JixjUnW1a8/A9a5R5k5wAFHZOYDsRIGX/6FMagU/qAeiyTYQ=
  matrix:
    - CONFIG_TYPE=gal

before_install:
  - 'gem update --force bundler'

before_script:
  - 'cp config/application.yml.example config/application.yml'
  - "psql -c 'create database mawidabp_test;' -U postgres"
  - 'bundle exec rails db:migrate'
  - 'slapd -f test/fixtures/ldap/slapd.conf -h ldap://localhost:3389'
  - 'bundle exec rails ldap:reset'
