language: ruby
cache: bundler
sudo: false
rvm:
  - 2.3.1
bundler_args: '--without development production'
addons:
  apt:
    packages:
    - imagemagick
    - slapd
    - ldap-utils
  postgresql: 9.5
before_script:
  - 'cp config/application.example.yml config/application.yml'
  - 'cp config/database.travis.yml config/database.yml'
  - 'bundle exec rake db:migrate'
  - 'slapd -f test/fixtures/ldap/slapd.conf -h ldap://localhost:3389'
  - 'bundle exec rake ldap:reset'
