HIDE_CONTROL_OBJECTIVE_ITEM_EFFECTIVENESS = ENV['HIDE_CONTROL_OBJECTIVE_ITEM_EFFECTIVENESS'] == 'true'
HIDE_CONTROL_OBJECTIVE_RISK = ENV['HIDE_CONTROL_OBJECTIVE_RISK'] == 'true'
HIDE_REVIEW_DESCRIPTION = ENV['HIDE_REVIEW_DESCRIPTION'] == 'true'
USE_SHORT_RELEVANCE = ENV['USE_SHORT_RELEVANCE'] == 'true'
