# Pesonalizado para cargar las configuraciones

DEFAULT_SETTINGS = {
  account_expire_time: 90,
  allow_concurrent_sessions: true,
  attempts_count: 3,
  brief_period_in_weeks: 0,
  exchange_directory_path: '/tmp',
  expire_notification: 15,
  finding_stale_confirmed_days: 3,
  password_constraint: '^(?=.*[a-zA-Z])(?=.*[0-9]).*$',
  password_count: 12,
  password_expire_time: 30,
  password_minimum_length: 8,
  password_minimum_time: 1,
  require_manager_on_findings: false,
  review_code_expresion: '^(\\d){2}-[A-Z]{2}-(\\d){2}-(\\d){2}$',
  session_expire_time: 15,
  show_follow_up_timestamps: true,
  show_print_date_on_pdfs: true,
  hide_import_from_ldap: false,
  skip_function_and_manager_from_ldap_sync: false,
  hide_obsolete_best_practices: false,
  hours_of_work_per_day: 0,
  conclusion_review_receiver: '_',
  temporary_polls: false,
  finding_warning_expire_days: [7, 1],
  finding_by_current_user: true,
  enable_close_date_edition: false,
  finding_days_for_next_notifications: [FINDING_DAYS_FOR_SECOND_NOTIFICATION],
  uniqueness_username_validation: true,
  skip_reiteration_copy: false,
  finding_state_change_notification: false,
  notify_recently_finalized_findings: false,
  review_filtered_by_user_assignments: false,
  review_permission_by_assignment: false
}.with_indifferent_access.freeze
