encoding: utf-8
markdown: kramdown
permalink: pretty
baseurl: "/help"
plugins:
  - jekyll-assets
  - jekyll-multiple-languages-plugin
assets:
  digest: true
  compress:
    css: true
    js: true
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/assets/stylesheets
    - _vendor/assets/javascripts
    - _vendor/assets/fonts
exclude:
  - Gemfile
  - Gemfile.lock
  - .asset-cache
  - .git
  - .gitignore
languages: ['es']
