encoding: utf-8
markdown: kramdown
permalink: pretty
baseurl: "/help"
gems:
  - jekyll-multiple-languages-plugin
assets:
  cache: false
  digest: true
  sources:
    - "_assets/images"
    - "_assets/javascripts"
    - "_assets/stylesheets"
    - "_vendor/assets/stylesheets"
    - "_vendor/assets/javascripts"
    - "_vendor/assets/fonts"
exclude:
  - Gemfile
  - Gemfile.lock
  - .git
  - .gitignore
languages: ['es']
