source 'https://rubygems.org'

gem 'jekyll', '~> 3.8.0'

gem 'sass'
gem 'coffee-script'
gem 'uglifier'
gem 'kramdown'
gem 'bootstrap-sass'
# Restricted only to support old node versions on some customers
gem 'autoprefixer-rails', '< 9'
# Restricted for customer
gem 'sprockets', '< 4'

group :jekyll_plugins do
  gem 'jekyll-assets'
  gem 'jekyll-multiple-languages-plugin'
end
