source 'https://rubygems.org'

gem 'jekyll', '~> 3.8.0'

gem 'sass'
gem 'coffee-script'
gem 'uglifier'
gem 'kramdown'
gem 'bootstrap-sass'
gem 'autoprefixer-rails', '< 10' # TODO: remove when all customers have node > 8
gem 'execjs', '< 2.8'
gem 'sprockets', '~> 3.7'

group :jekyll_plugins do
  gem 'jekyll-multiple-languages-plugin'
end
