source 'https://rubygems.org'

gem 'jekyll'

gem 'sass'
gem 'coffee-script'
gem 'uglifier'
gem 'kramdown'
gem 'bootstrap-sass'
# Restricted only to support old node versions on some customers
gem 'autoprefixer-rails', '< 9'

group :jekyll_plugins do
  gem 'jekyll-assets'
  gem 'jekyll-multiple-languages-plugin'
end
