SMTP_ADDRESS: 'smtp.gmail.com'
SMTP_PORT: '587'
SMTP_DOMAIN: 'gmail.com'
SMTP_USER_NAME: 'username@change.me'
SMTP_PASSWORD: '<password>'
SMTP_AUTHENTICATION: 'plain'
SMTP_ENABLE_STARTTLS_AUTO: 'true'

APP_HOST: 'lvh.me'
APP_PROTOCOL: 'http'
EMAIL_ADDRESS: 'noreply@change.me'

REDIS_HOST: 'localhost'
REDIS_PORT: '6379'

SECRET_KEY_BASE: 'REPLACE with rake secret output'
NEW_RELIC_LICENSE_KEY: 'REPLACE with the one provided by NewRelic'
RAILS_MASTER_KEY: 'REPLACE with THE master key'

# Extra application options
ALLOW_CONCLUSION_FINAL_REVIEW_DESTRUCTION: 'false'
ALLOW_FINDING_ASSUMED_RISK_TO_PENDING: 'false'
ALLOW_REVIEW_CONTROL_OBJECTIVE_DUPLICATION: 'false'
AUTOMATICALLY_SORT_FINDINGS_ON_CONCLUSION: '{"cirope":"recode_weaknesses_by_repetition_and_risk"}' # In JSON
COMMITMENT_DATE_LIMITS: '{"first_date": {"high": {"1.year": "Una observación de riesgo alto, no puede tener una fecha estimada de solución mayor a 1 año."}}, "reschedule": {"default": { "6.months": "No se puede reprogramar con una fecha mayor a 6 meses"}}}'
CONCLUSION_REVIEW_SORT_BY_RISK_START: ''
DEFAULT_LDAP_ROLES: ''
DISABLE_COI_AUDIT_DATE_VALIDATION: 'false'
DISABLE_FINDING_FINAL_STATE_ROLE_VALIDATION: 'false'
DISABLE_FINDINGS_EXPIRATION_NOTIFICATION: 'false'
DISABLE_REVIEW_AUDITED_VALIDATION: 'false'
ENABLE_PUBLIC_REGISTRATION: 'false'
EXTRA_USERS_INFO: '{}' # Example '{"path": "/some/path.csv", "format": "peoplesoft_txt"}'
FINDING_ANSWER_COMMITMENT_DATE_LIMITS: '{}'
FINDING_ANSWER_COMMITMENT_SUPPORT: 'true'
HIDE_BUSINESS_UNIT_SCORES: 'false'
HIDE_CONTROL_COMPLIANCE_TESTS: 'false'
HIDE_CONTROL_EFFECTS: 'false'
HIDE_CONTROL_OBJECTIVE_ITEM_EFFECTIVENESS: 'false'
HIDE_CONTROL_OBJECTIVE_RISK: 'false'
HIDE_FINDING_CRITERIA_MISMATCH: 'false'
HIDE_FINDING_IMPLEMENTED_AND_ASSUMED_RISK: 'false'
HIDE_OPORTUNITIES: 'false'
HIDE_REVIEW_DESCRIPTION: 'false'
HIDE_WEAKNESS_EFFECT: 'false'
NOTIFY_EXPIRED_AND_STALE_FOLLOW_UP: 'false'
NOTIFY_NEW_ADMIN: 'false'
ORDER_REVIEWS_BY: 'period'
ORDER_WEAKNESSES_ON_CONCLUSION_REVIEWS_BY: 'risk'
ORGANIZATIONS_WITH_BEST_PRACTICE_COMMENTS: ''
ORGANIZATIONS_WITH_CONTROL_OBJECTIVE_COUNTS: ''
ORGANIZATIONS_WITH_REVIEW_SCORE_BY_WEAKNESS: 'cirope'
PLAN_ITEM_REVIEW_CONCLUDED_ON: 'created_at'
REVIEW_SCORES: '{}' # In JSON and must be sorted by date in descending order
SCORE_BY_WEAKNESS: '{}' # In JSON
SHOW_ALTERNATIVE_QUESTIONNAIRES: 'false'
SHOW_ASSUMED_RISK_AS_REVIEW_PENDING: 'false'
SHOW_CONCLUSION_ALTERNATIVE_PDF: '{"cirope": "pat"}'
SHOW_CONCLUSION_AS_OPTIONS: 'false'
SHOW_CONDENSED_PRIORITIES: 'false'
SHOW_FINDING_CURRENT_SITUATION: 'true'
SHOW_ORGANIZATION_PREFIX_ON_REVIEW_NOTIFICATION: ''
SHOW_REVIEW_AUTOMATIC_IDENTIFICATION: 'false'
SHOW_REVIEW_BEST_PRACTICE_COMMENTS: 'false'
SHOW_REVIEW_EXTRA_ATTRIBUTES: 'false'
SHOW_SHORT_QUALIFICATIONS: 'false'
SHOW_WEAKNESS_EXTRA_ATTRIBUTES: 'false'
SHOW_WEAKNESS_PROGRESS: 'true'
USE_GLOBAL_WEAKNESS_REVIEW_CODE: ''
USE_SHORT_RELEVANCE: 'false'
USE_SCOPE_CYCLE: 'true'
WEAKNESS_SCORE_OBSOLESCENCE: '9'
WEAKNESS_SCORE_OBSOLESCENCE_START: '2019-01-01'
WEAKNESS_TAG_SYNC: 'false'
WEAKNESS_TAG_VALIDATION_START: ''
WEAKNESS_WEIGHTS: '{}' # In JSON

production:
  APP_PROTOCOL: 'https'
