SMTP_ADDRESS: 'smtp.gmail.com'
SMTP_PORT: '587'
SMTP_DOMAIN: 'gmail.com'
SMTP_USER_NAME: 'username@change.me'
SMTP_PASSWORD: '<password>'
SMTP_AUTHENTICATION: 'plain'
SMTP_ENABLE_STARTTLS_AUTO: 'true'

APP_HOST: 'lvh.me'
APP_PROTOCOL: 'http'
EMAIL_ADDRESS: 'noreply@change.me'

REDIS_HOST: 'localhost'
REDIS_PORT: '6379'

SECRET_KEY_BASE: 'REPLACE with rake secret output'
NEW_RELIC_LICENSE_KEY: 'REPLACE with the one provided by NewRelic'
RAILS_MASTER_KEY: 'REPLACE with THE master key'

# Extra application options
ALLOW_CONCLUSION_FINAL_REVIEW_DESTRUCTION: 'false'
ALLOW_FINDING_ASSUMED_RISK_TO_PENDING: 'false'
ALLOW_REVIEW_CONTROL_OBJECTIVE_DUPLICATION: 'false'
AUTOMATICALLY_SORT_FINDINGS_ON_CONCLUSION: '{}' # In JSON
CODE_CHANGE_DATES: '{}' # Example '{"custom_field1": "1999-01-01", "custom_field2": "1999-01-02"}'
COMMITMENT_DATE_LIMITS: '{}'
CONCLUSION_REVIEW_SORT_BY_RISK_START: ''
DEFAULT_LDAP_ROLES: ''
DISABLE_COI_AUDIT_DATE_VALIDATION: 'false'
DISABLE_FINDING_FINAL_STATE_ROLE_VALIDATION: 'false'
DISABLE_FINDINGS_EXPIRATION_NOTIFICATION: 'false'
DISABLE_REVIEW_AUDITED_VALIDATION: 'false'
ENABLE_USER_CREATION_WHEN_LDAP: 'false'
ENABLE_PUBLIC_REGISTRATION: 'true'
EXTRA_USERS_INFO: '{"google": {"path": "test/fixtures/files/peoplesoft_txt.txt", "role_path": "test/fixtures/files/mw_l_.csv", "format": "peoplesoft_txt"}}' # '{}'
FINDING_ANSWER_COMMITMENT_DATE_LIMITS: '{}'
FINDING_ANSWER_COMMITMENT_SUPPORT: 'false'
FINDING_REPEATABILITY_FILE: '{}'
HIDE_BUSINESS_UNIT_SCORES: 'false'
HIDE_CONTROL_COMPLIANCE_TESTS: 'false'
HIDE_CONTROL_EFFECTS: 'false'
HIDE_CONTROL_OBJECTIVE_ITEM_EFFECTIVENESS: 'false'
HIDE_CONTROL_OBJECTIVE_RISK: 'false'
HIDE_FINDING_CRITERIA_MISMATCH: 'false'
HIDE_FINDING_IMPLEMENTED_AND_ASSUMED_RISK: 'false'
HIDE_OPORTUNITIES: 'false'
HIDE_REVIEW_DESCRIPTION: 'false'
HIDE_WEAKNESS_EFFECT: 'false'
NOTIFY_NEW_ADMIN: 'false'
NOTIFY_EXPIRED_AND_STALE_FOLLOW_UP: 'true'
ORDER_REVIEWS_BY: 'period'
ORDER_WEAKNESSES_ON_CONCLUSION_REVIEWS_BY: 'control_objective_items'
ORGANIZATIONS_WITH_BEST_PRACTICE_COMMENTS: ''
ORGANIZATIONS_WITH_CONTROL_OBJECTIVE_COUNTS: ''
ORGANIZATIONS_WITH_REVIEW_SCORE_BY_WEAKNESS: ''
ORGANIZATIONS_WITH_INTERNAL_CONTROL_QUALIFICATION_REPORT: '[]'
PLAN_ITEM_REVIEW_CONCLUDED_ON: 'created_at'
REQUIRED_BY_OPTIONS_MEMO: '[]'
REVIEW_SCORES: '{}' # In JSON and must be sorted by date in descending order
RISK_WEIGHTS: '{ "none": 0, "low": 1, "medium": 2, "high": 3 }'
SCOPE_DETAIL_IN_CONCLUSION_REVIEW_START: ''
SCORE_BY_WEAKNESS: '{}' # In JSON
SHOW_ALTERNATIVE_QUESTIONNAIRES: 'false'
SHOW_ASSUMED_RISK_AS_REVIEW_PENDING: 'false'
SHOW_CONCLUSION_ALTERNATIVE_PDF: '{}' # In JSON
SHOW_CONCLUSION_AS_OPTIONS: 'false'
SHOW_CONDENSED_PRIORITIES: 'false'
SHOW_FINDING_CURRENT_SITUATION: 'false'
SHOW_MEMOS: 'false'
SHOW_ORGANIZATION_PREFIX_ON_REVIEW_NOTIFICATION: ''
SHOW_REVIEW_AUTOMATIC_IDENTIFICATION: 'false'
SHOW_REVIEW_BEST_PRACTICE_COMMENTS: 'false'
SHOW_REVIEW_EXTRA_ATTRIBUTES: 'false'
SHOW_SHORT_QUALIFICATIONS: 'false'
SHOW_WEAKNESS_EXTRA_ATTRIBUTES: 'false'
SHOW_WEAKNESS_PROGRESS: 'false'
USE_GLOBAL_WEAKNESS_REVIEW_CODE: ''
USE_SHORT_RELEVANCE: 'false'
USE_SCOPE_CYCLE: 'false'
WEAKNESS_SCORE_OBSOLESCENCE: ''
WEAKNESS_SCORE_OBSOLESCENCE_START: ''
WEAKNESS_TAG_COUNT_BY_ORGANIZATION: '{}'
WEAKNESS_TAG_SYNC: 'false'
WEAKNESS_TAG_VALIDATION_START: ''
WEAKNESS_WEIGHTS: '{}' # In JSON

production:
  APP_PROTOCOL: 'https'
