ALLOW_CONCLUSION_FINAL_REVIEW_DESTRUCTION: 'true'
ALLOW_FINDING_ASSUMED_RISK_TO_PENDING: 'true'
ALLOW_REVIEW_CONTROL_OBJECTIVE_DUPLICATION: 'true'
DEFAULT_LDAP_ROLES: ''
DISABLE_FINDING_FINAL_STATE_ROLE_VALIDATION: 'true'
DISABLE_FINDINGS_EXPIRATION_NOTIFICATION: 'true'
DISABLE_REVIEW_AUDITED_VALIDATION_ON_CREATION: 'true'
HIDE_BUSINESS_UNIT_SCORES: 'true'
HIDE_CONTROL_COMPLIANCE_TESTS: 'true'
HIDE_CONTROL_EFFECTS: 'true'
HIDE_CONTROL_OBJECTIVE_ITEM_EFFECTIVENESS: 'true'
HIDE_CONTROL_OBJECTIVE_RISK: 'true'
HIDE_FINDING_CRITERIA_MISMATCH: 'true'
HIDE_OPORTUNITIES: 'true'
HIDE_REVIEW_DESCRIPTION: 'true'
HIDE_WEAKNESS_EFFECT: 'true'
HIDE_WEAKNESS_PRIORITY: 'true'
ORDER_REVIEWS_BY: 'conclusion_final_review'
ORDER_WEAKNESSES_ON_CONCLUSION_REVIEWS_BY: 'control_objective_items'
ORGANIZATIONS_WITH_BEST_PRACTICE_COMMENTS: 'cirope'
ORGANIZATIONS_WITH_CONTROL_OBJECTIVE_COUNTS: 'cirope'
ORGANIZATIONS_WITH_REVIEW_SCORE_BY_WEAKNESS: ''
PLAN_ITEM_REVIEW_CONCLUDED_ON: 'issue_date'
SHOW_ASSUMED_RISK_AS_REVIEW_PENDING: 'true'
SHOW_CONCLUSION_ALTERNATIVE_PDF: 'true'
SHOW_CONCLUSION_AS_OPTIONS: 'true'
SHOW_EXTENDED_RISKS: 'true'
SHOW_FINDING_CURRENT_SITUATION: 'true'
SHOW_ORGANIZATION_PREFIX_ON_REVIEW_NOTIFICATION: 'cirope'
SHOW_REVIEW_AUTOMATIC_IDENTIFICATION: 'true'
SHOW_REVIEW_EXTRA_ATTRIBUTES: 'true'
SHOW_REVIEW_BEST_PRACTICE_COMMENTS: 'true'
SHOW_SHORT_QUALIFICATIONS: 'true'
SHOW_WEAKNESS_EXTRA_ATTRIBUTES: 'true'
SHOW_WEAKNESS_PROGRESS: 'true'
USE_SHORT_RELEVANCE: 'true'

