SMTP_ADDRESS: 'smtp.gmail.com'
SMTP_PORT: '587'
SMTP_DOMAIN: 'gmail.com'
SMTP_USER_NAME: 'username@change.me'
SMTP_PASSWORD: '<password>'
SMTP_AUTHENTICATION: 'plain'
SMTP_ENABLE_STARTTLS_AUTO: 'true'

APP_HOST: 'lvh.me'
APP_PROTOCOL: 'http'
EMAIL_ADDRESS: 'noreply@change.me'

SECRET_KEY_BASE: 'REPLACE with rake secret output'
NEW_RELIC_LICENSE_KEY: 'REPLACE with the one provided by NewRelic'

# Extra options
DISABLE_FINDINGS_EXPIRATION_NOTIFICATION: 'false'
HIDE_CONTROL_OBJECTIVE_ITEM_EFFECTIVENESS: 'false'
HIDE_CONTROL_OBJECTIVE_RISK: 'false'
HIDE_REVIEW_DESCRIPTION: 'false'
USE_SHORT_RELEVANCE: 'false'

production:
  APP_PROTOCOL: 'https'
