ALLOW_CONCLUSION_FINAL_REVIEW_DESTRUCTION: 'false'
ALLOW_FINDING_ASSUMED_RISK_TO_PENDING: 'false'
ALLOW_REVIEW_CONTROL_OBJECTIVE_DUPLICATION: 'false'
DEFAULT_LDAP_ROLES: ''
DISABLE_FINDING_FINAL_STATE_ROLE_VALIDATION: 'false'
DISABLE_FINDINGS_EXPIRATION_NOTIFICATION: 'false'
DISABLE_REVIEW_AUDITED_VALIDATION_ON_CREATION: 'false'
HIDE_BUSINESS_UNIT_SCORES: 'false'
HIDE_CONTROL_COMPLIANCE_TESTS: 'false'
HIDE_CONTROL_EFFECTS: 'false'
HIDE_CONTROL_OBJECTIVE_ITEM_EFFECTIVENESS: 'false'
HIDE_CONTROL_OBJECTIVE_RISK: 'false'
HIDE_FINDING_CRITERIA_MISMATCH: 'false'
HIDE_OPORTUNITIES: 'false'
HIDE_REVIEW_DESCRIPTION: 'false'
HIDE_WEAKNESS_EFFECT: 'false'
HIDE_WEAKNESS_PRIORITY: 'false'
ORDER_REVIEWS_BY: 'period'
ORDER_WEAKNESSES_ON_CONCLUSION_REVIEWS_BY: 'control_objective_items'
ORGANIZATIONS_WITH_BEST_PRACTICE_COMMENTS: ''
ORGANIZATIONS_WITH_CONTROL_OBJECTIVE_COUNTS: ''
ORGANIZATIONS_WITH_REVIEW_SCORE_BY_WEAKNESS: ''
PLAN_ITEM_REVIEW_CONCLUDED_ON: 'created_at'
SHOW_ASSUMED_RISK_AS_REVIEW_PENDING: 'false'
SHOW_CONCLUSION_ALTERNATIVE_PDF: 'false'
SHOW_CONCLUSION_AS_OPTIONS: 'false'
SHOW_EXTENDED_RISKS: 'false'
SHOW_FINDING_CURRENT_SITUATION: 'false'
SHOW_ORGANIZATION_PREFIX_ON_REVIEW_NOTIFICATION: ''
SHOW_REVIEW_AUTOMATIC_IDENTIFICATION: 'false'
SHOW_REVIEW_EXTRA_ATTRIBUTES: 'false'
SHOW_REVIEW_BEST_PRACTICE_COMMENTS: 'false'
SHOW_SHORT_QUALIFICATIONS: 'false'
SHOW_WEAKNESS_EXTRA_ATTRIBUTES: 'false'
SHOW_WEAKNESS_PROGRESS: 'false'
USE_SHORT_RELEVANCE: 'false'
