SMTP_ADDRESS: 'smtp.gmail.com'
SMTP_PORT: '587'
SMTP_DOMAIN: 'gmail.com'
SMTP_USER_NAME: 'username@change.me'
SMTP_PASSWORD: '<password>'
SMTP_AUTHENTICATION: 'plain'
SMTP_ENABLE_STARTTLS_AUTO: 'true'

APP_HOST: 'lvh.me'
APP_PROTOCOL: 'http'
EMAIL_ADDRESS: 'noreply@change.me'

REDIS_HOST: 'localhost'
REDIS_PORT: '6379'

SECRET_KEY_BASE: 'REPLACE with rake secret output'
NEW_RELIC_LICENSE_KEY: 'REPLACE with the one provided by NewRelic'
RAILS_MASTER_KEY: 'REPLACE with THE master key'

# Extra application options
ALLOW_CONCLUSION_FINAL_REVIEW_DESTRUCTION: 'false'
ALLOW_FINDING_ASSUMED_RISK_TO_PENDING: 'false'
ALLOW_REVIEW_CONTROL_OBJECTIVE_DUPLICATION: 'false'
AUTOMATICALLY_SORT_FINDINGS_ON_CONCLUSION: '{}' # In JSON
CODE_CHANGE_DATES: '{}' # Example '{"custom_field1": "1999-01-01", "custom_field2": "1999-01-02"}'
COMMITMENT_DATE_LIMITS: '{}'
CONCLUSION_REVIEW_SORT_BY_RISK_START: ''
DEFAULT_LDAP_ROLES: ''
DISABLE_COI_AUDIT_DATE_VALIDATION: 'false'
DISABLE_FINDING_FINAL_STATE_ROLE_VALIDATION: 'true'
DISABLE_FINDINGS_EXPIRATION_NOTIFICATION: 'false'
DISABLE_REVIEW_AUDITED_VALIDATION: 'false'
ENABLE_USER_CREATION_WHEN_LDAP: 'false'
ENABLE_PUBLIC_REGISTRATION: 'false'
EXTRA_USERS_INFO: '{"cirope": {"path": "test/fixtures/files/bpat.csv", "role_path": "", "format": "pat_txt", "header": {"name": "Nombres", "lastname": "Apellidos", "user": "Usuario Meta4", "email": "Correo Electronico"}}}'
FILE_UPLOADS_CONSTRAINTS: '{}'
FINDING_ANSWER_COMMITMENT_DATE_LIMITS: '{}'
FINDING_ANSWER_COMMITMENT_SUPPORT: 'false'
FINDING_REPEATABILITY_FILE: '{"cirope": "test/fixtures/files/repeticiones.csv"}'
HIDE_BUSINESS_UNIT_SCORES: 'false'
HIDE_CONTROL_COMPLIANCE_TESTS: 'false'
HIDE_CONTROL_EFFECTS: 'false'
HIDE_CONTROL_OBJECTIVE_ITEM_EFFECTIVENESS: 'false'
HIDE_CONTROL_OBJECTIVE_RISK: 'true'
HIDE_FINDING_CRITERIA_MISMATCH: 'true'
HIDE_FINDING_IMPLEMENTED_AND_ASSUMED_RISK: 'false'
HIDE_OPORTUNITIES: 'false'
HIDE_REVIEW_DESCRIPTION: 'false'
HIDE_WEAKNESS_EFFECT: 'false'
NOTIFY_EXPIRED_AND_STALE_FOLLOW_UP: 'true'
NOTIFY_NEW_ADMIN: 'false'
ORDER_REVIEWS_BY: 'conclusion_final_review'
ORDER_WEAKNESSES_ON_CONCLUSION_REVIEWS_BY: 'control_objective_items'
ORGANIZATIONS_WITH_BEST_PRACTICE_COMMENTS: ''
ORGANIZATIONS_WITH_CONTROL_OBJECTIVE_COUNTS: ''
ORGANIZATIONS_WITH_REVIEW_SCORE_BY_WEAKNESS: 'cirope'
ORGANIZATIONS_WITH_INTERNAL_CONTROL_QUALIFICATION_REPORT: '[]'
PLAN_ITEM_REVIEW_CONCLUDED_ON: 'created_at'
REQUIRED_BY_OPTIONS_MEMO: '[]'
REVIEW_SCORES: '{"2000-01-01": { "satisfactory": 80, "improve": 55, "regular": 28 }}'
RISK_WEIGHTS: '{}'
SCOPE_DETAIL_IN_CONCLUSION_REVIEW_START: ''
SCORE_BY_WEAKNESS: '{"require_some_improvements": 79, "require_improvements": 54, "require_lots_of_improvements": 0}'
SHARED_SESSION: 'false'
SHOW_ALTERNATIVE_QUESTIONNAIRES: 'false'
SHOW_ASSUMED_RISK_AS_REVIEW_PENDING: 'false'
SHOW_CONCLUSION_ALTERNATIVE_PDF: '{"cirope": "pat"}'
SHOW_CONCLUSION_AS_OPTIONS: 'false'
SHOW_CONDENSED_PRIORITIES: 'false'
SHOW_FINDING_CURRENT_SITUATION: 'true'
SHOW_ORGANIZATION_PREFIX_ON_REVIEW_NOTIFICATION: ''
SHOW_MEMOS: 'false'
SHOW_REVIEW_AUTOMATIC_IDENTIFICATION: 'false'
SHOW_REVIEW_BEST_PRACTICE_COMMENTS: 'false'
SHOW_REVIEW_EXTRA_ATTRIBUTES: 'false'
SHOW_SHORT_QUALIFICATIONS: 'false'
SHOW_WEAKNESS_EXTRA_ATTRIBUTES: 'false'
SHOW_WEAKNESS_PROGRESS: 'true'
USE_GLOBAL_WEAKNESS_REVIEW_CODE: 'cirope'
USE_SHORT_RELEVANCE: 'false'
USE_SCOPE_CYCLE: 'true'
WEAKNESS_SCORE_OBSOLESCENCE: ''
WEAKNESS_SCORE_OBSOLESCENCE_START: ''
WEAKNESS_TAG_COUNT_BY_ORGANIZATION: '{}'
WEAKNESS_TAG_SYNC: 'false'
WEAKNESS_TAG_VALIDATION_START: '2021-12-03'
WEAKNESS_WEIGHTS: '{"normal_high": 4.0, "repeated_high": 6.0, "old_high": 10.5, "old_medium": 8.5, "old_low": 7.0}'

production:
  APP_PROTOCOL: 'https'
