default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['TRAVIS'] ? 'postgres' : 'mawidabp' %>
  password: <%= ENV['TRAVIS'] ? '' : 'mawidabp' %>
  host: 127.0.0.1
  port: 5432

development:
  <<: *default
  database: mawidabp_development

test:
  <<: *default
  database: mawidabp_test

production:
  <<: *default
  database: mawidabp_production

sandbox:
  <<: *default
  database: mawidabp_production
