default: &default
  adapter: <%= ENV['DB_ADAPTER'] || 'postgresql' %>
  encoding: unicode
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  port: 5432
  pool: 5
  username: <%= ENV['TRAVIS'] ? 'postgres' : ENV['DB_USER'] || 'mawidabp' %>
  password: <%= ENV['TRAVIS'] ? 'postgres' : ENV['DB_PASSWORD'] || 'mawidabp' %>

development:
  <<: *default
  database: mawidabp_development

test:
  <<: *default
  database: mawidabp_test

production:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'mawidabp_production' %>

sandbox:
  <<: *default
  database: mawidabp_production
