common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['TRAVIS'] ? 'postgres' : 'mawidabp' %>
  password: <%= ENV['TRAVIS'] ? '' : 'mawidabp' %>

development:
  database: mawidabp_development
  <<: *common

test:
  database: mawidabp_test
  <<: *common

production:
  database: mawidabp_production
  <<: *common

sandbox:
  database: mawidabp_production
  <<: *common
