common: &common
  adapter: oracle_enhanced
  pool: 5
  username: <%= ENV['TRAVIS'] ? 'postgres' : 'system' %>
  password: <%= ENV['TRAVIS'] ? '' : 'oracle' %>

development:
  database: //localhost:1521/xe
  <<: *common

test:
  adapter: sqlite3
  database: db/test.sqlite3

production:
  database: xe
  <<: *common

sandbox:
  database: xe
  <<: *common
