service: mawidabp

image: mawidabp

servers:
  web:
    hosts:
      - <%= ENV['HOST'] || '127.0.0.1' %>
    labels:
      traefik.http.routers.mawidabp.entrypoints: websecure
      traefik.http.routers.mawidabp.rule: Host(`<%= ENV['HOST'] %>`) || Host(`admin-<%= ENV['HOST'] %>`)
      traefik.http.routers.mawidabp.tls.certresolver: letsencrypt
  job:
    hosts:
      - <%= ENV['HOST'] || '127.0.0.1' %>
    cmd: bundle exec sidekiq

registry:
  server: 030650017690.dkr.ecr.us-east-1.amazonaws.com
  username: AWS
  password: <%= %x(aws ecr get-login-password) %>

env:
  clear:
    DB_HOST: <%= ENV['HOST'] || '127.0.0.1' %>
    REDIS_HOST: <%= ENV['HOST'] || '127.0.0.1' %>
  secret:
    - POSTGRES_PASSWORD

builder:
  remote:
    arch: <%= ENV['ARCH'].present? ? ENV['ARCH'] : (raise RuntimeError.new('Debe agregar el argumento ARCH con los valores(arm64 o amd64)')) %>
    host: ssh://root@<%= ENV['HOST'] %>

accessories:
  postgresql:
    image: postgres:16
    host: <%= ENV['HOST'] || '127.0.0.1' %>
    port: 5432
    env:
      clear:
        POSTGRES_USER: 'mawidabp'
        POSTGRES_DB: 'mawidabp_production'
      secret:
        - POSTGRES_PASSWORD
    files:
      - db/production.sql:/docker-entrypoint-initdb.d/setup.sql
    volume:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    port: 6379
    roles:
      - web
      - job
    cmd: "redis-server"
    volumes:
      - /var/lib/redis:/data

traefik:
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json"
  args:
    accesslog: true
    accesslog.format: json
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    entryPoints.web.http.redirections.entryPoint.to: websecure # We want to force https
    entryPoints.web.http.redirections.entryPoint.scheme: https
    entryPoints.web.http.redirections.entrypoint.permanent: true
    entrypoints.websecure.http.tls.domains[0].main: <%= ENV['HOST'] %>
    entrypoints.websecure.http.tls.domains[0].sans: "admin-<%= ENV['HOST'] %>"
    certificatesResolvers.letsencrypt.acme.email: "soporte@mawidabp.com"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web

healthcheck:
  path: /healthy
