service: mawidabp

image: mawidabp

servers:
  web:
    hosts:
      - 34.231.104.28
    labels:
      traefik.http.routers.mawidabp.entrypoints: websecure
      traefik.http.routers.mawidabp.rule: Host(`kamal.mawidabp.com`)
      traefik.http.routers.mawidabp.tls.certresolver: letsencrypt
      #traefik.http.routers.mawidabp.tls.domains.main: "kamal.mawidabp.com"
      #traefik.http.routers.mawidabp.tls.domains.sans: "admin-kamal.mawidabp.com"
  job:
    hosts:
      - 34.231.104.28
    cmd: bundle exec sidekiq

registry:
  server: 030650017690.dkr.ecr.us-east-1.amazonaws.com
  username: AWS
  password: <%= %x(aws ecr get-login-password) %>

env:
  clear:
    DB_HOST: 34.231.104.28
    REDIS_HOST: "34.231.104.28"
  secret:
    - POSTGRES_PASSWORD

builder:
  remote:
    arch: arm64
    host: ssh://root@34.231.104.28

accessories:
  postgresql:
    image: postgres:16
    host: 34.231.104.28
    port: 5432
    env:
      clear:
        POSTGRES_USER: 'mawidabp'
        POSTGRES_DB: 'mawidabp_production'
      secret:
        - POSTGRES_PASSWORD
    files:
      - db/production.sql:/docker-entrypoint-initdb.d/setup.sql
    volume:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    port: 6379
    roles:
      - web
      - job
    cmd: "redis-server"
    volumes:
      - /var/lib/redis:/data

traefik:
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json"
  args:
    accesslog: true
    accesslog.format: json
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    entryPoints.web.http.redirections.entryPoint.to: websecure # We want to force https
    entryPoints.web.http.redirections.entryPoint.scheme: https
    entryPoints.web.http.redirections.entrypoint.permanent: true
    certificatesResolvers.letsencrypt.acme.email: "sergio@hullop.com"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web

healthcheck:
  path: /healthy
