// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails

import 'jquery'
import 'jquery_ujs'
import 'jquery-ui/effects/effect-highlight'
import 'jquery-ui/widgets/autocomplete'
import 'jquery-ui/widgets/datepicker'
import 'jquery-ui/i18n/datepicker-es'
import 'jquery-ui/widgets/dialog'
import 'jquery-ui/widgets/sortable'

import 'jquery.url'
import 'jquery.mw'

import '@popperjs/core'
import 'bootstrap'

import 'simplebar'
import 'sidebar'

import 'apexcharts'
import 'apexcharts/es'

import 'add_days_to_input'
import 'ajax'
import 'autocomplete'
import 'best_practices'
import 'checkbox'
import 'checkbox_enable_disable_inputs'
import 'closing_interviews'
import 'common'
import 'conclusion_draft_reviews'
import 'control_objective_items'
import 'date_pickers'
import 'documents'
import 'dynamic_form'
import 'enable_disable_card_fieldset'
import 'endless_pagination'
import 'extensions'
import 'fetch'
import 'filters'
import 'findings'
import 'findings/answers'
import 'findings/work_papers'
import 'form_modification'
import 'form_submit'
import 'hide'
import 'input_text_only_accept_numerics'
import 'licenses'
import 'memos'
import 'needs_confirm_form'
import 'news'
import 'opening_interviews'
import 'permalinks'
import 'plan_items'
import 'plans'
import 'plans/calendar'
import 'plans/resources'
import 'plans/stats'
import 'process_controls'
import 'readings'
import 'reviews'
import 'risk_assessment_templates'
import 'risk_assessments'
import 'select_change_label'
import 'select_enable_checkbox'
import 'sessions'
import 'show'
import 'tags'
import 'tasks'
import 'time_summary'
import 'touch'
import 'users'
import 'wicked_pdf/number_pages'
import 'weakness_templates'
import 'weaknesses'
import 'work_papers'

import '@rails/activestorage'
import 'direct_upload'
