name: CI
on:
  push:
    branches:
      - master
      - c-banco-china
      - c-bancotdf
      - c-bica
      - c-bice-production
      - c-bna-aud
      - c-bna-pla
      - c-bvalores
      - c-bvalores-test
      - c-comafi-production
      - c-comafi-test
      - c-dino-production
      - c-galicia-production
      - c-galicia-test
      - c-hipotecario-production
      - c-hipotecario-testing
      - c-macro-production
      - c-macro-test
      - c-mariva-production
      - c-mariva-testing
      - c-nbch
      - c-patagonia-production
      - c-patagonia-test
      - c-petersen-production
      - c-petersen-test
      - c-smg-production
      - c-smg-test
      - c-supervielle-production
      - c-supervielle-test
  pull_request:
    branches:
      - master
      - c-banco-china
      - c-bancotdf
      - c-bica
      - c-bice-production
      - c-bna-aud
      - c-bna-pla
      - c-bvalores
      - c-bvalores-test
      - c-comafi-production
      - c-comafi-test
      - c-dino-production
      - c-galicia-production
      - c-galicia-test
      - c-hipotecario-production
      - c-hipotecario-testing
      - c-macro-production
      - c-macro-test
      - c-mariva-production
      - c-mariva-testing
      - c-nbch
      - c-patagonia-production
      - c-patagonia-test
      - c-petersen-production
      - c-petersen-test
      - c-smg-production
      - c-smg-test
      - c-supervielle-production
      - c-supervielle-test
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - 3.1
        config-type:
          - normal
          - gal
          - bic
          - bh
          - cycle_score
          - reviews_scored_by_weakness
        use_v31:
          - >-
            ${{ contains(github.ref_name, 'master')
            || contains(github.ref_name, 'china')
            || contains(github.ref_name, 'bancotdf')
            || contains(github.ref_name, 'bica')
            || contains(github.ref_name, 'bice')
            || contains(github.ref_name, 'bna')
            || contains(github.ref_name, 'bvalores')
            || contains(github.ref_name, 'comafi')
            || contains(github.ref_name, 'dino')
            || contains(github.ref_name, 'galicia')
            || contains(github.ref_name, 'hipotecario')
            || contains(github.ref_name, 'macro')
            || contains(github.ref_name, 'mariva')
            || contains(github.ref_name, 'nbch')
            || contains(github.ref_name, 'patagonia')
            || contains(github.ref_name, 'petersen')
            || contains(github.ref_name, 'smg')
            || contains(github.ref_name, 'supervielle')
            || contains(github.event.pull_request.base.ref, 'master')
            || contains(github.event.pull_request.base.ref, 'china')
            || contains(github.event.pull_request.base.ref, 'bancotdf')
            || contains(github.event.pull_request.base.ref, 'bica')
            || contains(github.event.pull_request.base.ref, 'bice')
            || contains(github.event.pull_request.base.ref, 'bna')
            || contains(github.event.pull_request.base.ref, 'bvalores')
            || contains(github.event.pull_request.base.ref, 'comafi')
            || contains(github.event.pull_request.base.ref, 'dino')
            || contains(github.event.pull_request.base.ref, 'galicia')
            || contains(github.event.pull_request.base.ref, 'hipotecario')
            || contains(github.event.pull_request.base.ref, 'macro')
            || contains(github.event.pull_request.base.ref, 'mariva')
            || contains(github.event.pull_request.base.ref, 'nbch')
            || contains(github.event.pull_request.base.ref, 'patagonia')
            || contains(github.event.pull_request.base.ref, 'petersen')
            || contains(github.event.pull_request.base.ref, 'smg')
            || contains(github.event.pull_request.base.ref, 'supervielle') }}
        use_bh:
          - >-
            ${{ contains(github.ref_name, 'master')
            || contains(github.ref_name, 'hipotecario')
            || contains(github.event.pull_request.base.ref, 'master')
            || contains(github.event.pull_request.base.ref, 'hipotecario') }}
        use_bic:
          - >-
            ${{ contains(github.ref_name, 'master')
            || contains(github.ref_name, 'bice')
            || contains(github.event.pull_request.base.ref, 'master')
            || contains(github.event.pull_request.base.ref, 'bice') }}
        use_cycle_score:
          - >-
            ${{ contains(github.ref_name, 'master')
            || contains(github.ref_name, 'patagonia')
            || contains(github.event.pull_request.base.ref, 'master')
            || contains(github.event.pull_request.base.ref, 'patagonia') }}
        use_gal:
          - >-
            ${{ contains(github.ref_name, 'master')
            || contains(github.ref_name, 'galicia')
            || contains(github.event.pull_request.base.ref, 'master')
            || contains(github.event.pull_request.base.ref, 'galicia') }}
        use_normal:
          - >-
            ${{ contains(github.ref_name, 'master')
            || contains(github.ref_name, 'china')
            || contains(github.ref_name, 'bancotdf')
            || contains(github.ref_name, 'bica')
            || contains(github.ref_name, 'bna')
            || contains(github.ref_name, 'bvalores')
            || contains(github.ref_name, 'comafi')
            || contains(github.ref_name, 'dino')
            || contains(github.ref_name, 'macro')
            || contains(github.ref_name, 'mariva')
            || contains(github.ref_name, 'petersen')
            || contains(github.ref_name, 'smg')
            || contains(github.ref_name, 'supervielle')
            || contains(github.event.pull_request.base.ref, 'master')
            || contains(github.event.pull_request.base.ref, 'china')
            || contains(github.event.pull_request.base.ref, 'bancotdf')
            || contains(github.event.pull_request.base.ref, 'bica')
            || contains(github.event.pull_request.base.ref, 'bna')
            || contains(github.event.pull_request.base.ref, 'bvalores')
            || contains(github.event.pull_request.base.ref, 'comafi')
            || contains(github.event.pull_request.base.ref, 'dino')
            || contains(github.event.pull_request.base.ref, 'macro')
            || contains(github.event.pull_request.base.ref, 'mariva')
            || contains(github.event.pull_request.base.ref, 'petersen')
            || contains(github.event.pull_request.base.ref, 'smg')
            || contains(github.event.pull_request.base.ref, 'supervielle') }}
        use_reviews_scored_by_weakness:
          - >-
            ${{ contains(github.ref_name, 'master')
            || contains(github.ref_name, 'nbch')
            || contains(github.event.pull_request.base.ref, 'master')
            || contains(github.event.pull_request.base.ref, 'nbch') }}
        exclude:
          - use_v31: false
            ruby-version: 3.1
          - use_bh: false
            config-type: bh
          - use_normal: false
            config-type: normal
          - use_gal: false
            config-type: gal
          - use_bic: false
            config-type: bic
          - use_cycle_score: false
            config-type: cycle_score
          - use_reviews_scored_by_weakness: false
            config-type: reviews_scored_by_weakness
    services:
      postgres:
        image: postgres:14
        ports:
          - '5432:5432'
        env:
          POSTGRES_DB: mawidabp_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports:
          - '6379:6379'
        options: --entrypoint redis-server
    env:
      RAILS_ENV: test
      GH_ACTIONS: true
      DATABASE_URL: "postgres://postgres:postgres@localhost:5432/mawidabp_test"
      REDIS_URL: redis://localhost:6379/0
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
      APP_HOST: 'lvh.me'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Update package lists
        run: sudo apt update
      - name: Install slapd and ldap-utils
        run: sudo apt -y install slapd ldap-utils
      - name: Install wkhtmltopdf
        run: sudo apt -y install wkhtmltopdf
      - name: Install ghostscript
        run: sudo apt install ghostscript
      - name: Modify ImageMagick policy
        run: sudo sed -i '/PDF/s/rights="none"/rights="read|write"/' /etc/ImageMagick-6/policy.xml
      - name: Install ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Migrate database
        run: bin/rails db:migrate
      - name: Copy application.yml
        run: cp config/application.${{ matrix.config-type }}.yml config/application.yml
      - name: Set up and run slpad
        run: |
          sudo cp test/fixtures/ldap/slapd.conf /etc/ldap/
          sudo slapd -f /etc/ldap/slapd.conf -h ldap://localhost:3389
          bundle exec rails ldap:reset
      - name: Run tests
        run: bin/rails test
